image: python:3.7
stages:
  - pages

pages:
  stage: pages
  script:
  - pip install sphinx
  - pip install sphinxcontrib-blockdiag sphinxcontrib-nwdiag sphinx_rtd_theme
  - make -C ja html
  - make -C en html
  - ls ja/build/html
  - ls en/build/html
  - mv en/build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - main
