image: sphinxdoc/sphinx-latexpdf:latest
stages:
  - pages

pages:
  stage: pages
  script:
  - make -C ja html
  - make -C en html
  - mkdir .public
  - mv ja/html .public/ja
  - mv en/html .public/en
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - main
