fapppx -A -d ./rep1  -Icpupa,nompi -tcsv -o pa1.csv
fapppx -A -d ./rep2  -Icpupa,nompi -tcsv -o pa2.csv
fapppx -A -d ./rep3  -Icpupa,nompi -tcsv -o pa3.csv
fapppx -A -d ./rep4  -Icpupa,nompi -tcsv -o pa4.csv
fapppx -A -d ./rep5  -Icpupa,nompi -tcsv -o pa5.csv
fapppx -A -d ./rep6  -Icpupa,nompi -tcsv -o pa6.csv
fapppx -A -d ./rep7  -Icpupa,nompi -tcsv -o pa7.csv
fapppx -A -d ./rep8  -Icpupa,nompi -tcsv -o pa8.csv
fapppx -A -d ./rep9  -Icpupa,nompi -tcsv -o pa9.csv
fapppx -A -d ./rep10 -Icpupa,nompi -tcsv -o pa10.csv
fapppx -A -d ./rep11 -Icpupa,nompi -tcsv -o pa11.csv
fapppx -A -d ./rep12 -Icpupa,nompi -tcsv -o pa12.csv
fapppx -A -d ./rep13 -Icpupa,nompi -tcsv -o pa13.csv
fapppx -A -d ./rep14 -Icpupa,nompi -tcsv -o pa14.csv
fapppx -A -d ./rep15 -Icpupa,nompi -tcsv -o pa15.csv
fapppx -A -d ./rep16 -Icpupa,nompi -tcsv -o pa16.csv
fapppx -A -d ./rep17 -Icpupa,nompi -tcsv -o pa17.csv
